version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    networks:
      - markdown-app
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    networks:
      - markdown-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - markdown-app
networks:
  markdown-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local